### ISSUE TITLE
征集一些新功能建议或者新UI库支持

### ISSUE THREAD

**Issue by Simon-He95** [Simon-He95/common-intellisense#56]

**Comment by FerretAngel** [comment]
添加对varlet3的支持
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/58507654/ced1acf9-81e0-499b-8933-c9c3bd781e1c)
![image](https://github.com/Simon-He95/vscode-common-intellisense/assets/58507654/35c99c99-c44d-40cd-9f33-c0c36253a439)

**Comment by Simon-He95** [comment]
v0.1.34 has supported varlet3

**Comment by redwolf1996** [comment]
支持uniapp和uni-ui  wot-design-uni 吗，这些用的人还是挺多的

**Comment by Simon-He95** [comment]
> 支持uniapp和uni-ui wot-design-uni 吗，这些用的人还是挺多的

If the [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) exceeds 20, it will be added to the supported plan

**Comment by kagol** [comment]
Suggest to support TinyVue: [#64](https://github.com/Simon-He95/vscode-common-intellisense/issues/64)

**Comment by Simon-He95** [comment]
> Suggest to support TinyVue: [#64](https://github.com/Simon-He95/vscode-common-intellisense/issues/64)

If the [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) exceeds 20, it will be added to the supported plan

**Comment by angelanana** [comment]
希望能支持view-design v4, UI库链接：https://v4.iviewui.com/

**Comment by Simon-He95** [comment]
> 希望能支持view-design v4, UI库链接：https://v4.iviewui.com/ Hope to support view-design v4, its website: https://v4.iviewui.com/ maybe I can help?

pr welcome :)

**Comment by Simon-He95** [comment]
> 是否可以支持react 的UI库

如果库很流行，用的人多，会考虑的

**Comment by TBXark** [comment]
nutui  https://github.com/jdf2e/nutui

**Comment by Simon-He95** [comment]
> nutui [jdf2e/nutui](https://github.com/jdf2e/nutui)

we have supported nutui with vue version

**Comment by Simon-He95** [comment]
> 希望能支持view-design v4, UI库链接：[v4.iviewui.com](https://v4.iviewui.com/) Hope to support view-design v4, its website: [v4.iviewui.com](https://v4.iviewui.com/) maybe I can help?

最新版本已经支持了 View UI Plus

**Comment by 5565007** [comment]
https://wot-design-uni.netlify.app/这个库

**Comment by Moonofweisheng** [comment]
> 支持uniapp和uni-ui wot-design-uni 吗，这些用的人还是挺多的

希望可以支持下[wot-design-uni](https://github.com/Moonofweisheng/wot-design-uni)

**Comment by chenyulun** [comment]
通过提交到插件仓库感觉不是上策，
应该定义一个规范，然后可以配置路径读取，这样各种组件都可以支持，我们还有内网的UI组件没办法发布到外网

如果已经实现了，请告知一下，感谢各位大佬

**Comment by Simon-He95** [comment]
> 通过提交到插件仓库感觉不是上策， 应该定义一个规范，然后可以配置路径读取，这样各种组件都可以支持，我们还有内网的UI组件没办法发布到外网
> 
> 如果已经实现了，请告知一下，感谢各位大佬

你可以不用提交，直接打包成 vscode 插件产物，内部去分享使用 https://github.com/Simon-He95/common-intellisense/issues/67

**Comment by chenyulun** [comment]
把项目的dependencies的依赖都扫一遍，然后找到对应包的`package.json`
并且找到有定义`common-intellisense`字段的包，并且读取配置
```json
{
name: '@abc/ui'
"common-intellisense": {
uiConfig: './common-intellisense',
name: 'abcui'
}
}
```
```js
import { propsReducer, componentsReducer,  } from '@xxx/abc/common-intellisense'
// constants.ts的内容补充 
// UINames ==> @xxx/abc
// nameMap ==> {'@xxx/abc': 'abcui' }
```
也能文档更新了也能及时识别更新

之前的@vue/cli好像就扫描了前缀是vue-plugin-之类的包然后内部自动注册

如果可以的话我可以尝试这个PR
by the way: 数据字段的文档也需要补充，现在只能先看照描画虎，先看其他人的定义，或者去看源码了解可以配置那些字段

**Comment by Simon-He95** [comment]
> 把项目的dependencies的依赖都扫一遍，然后找到对应包的`package.json` 并且找到有定义`common-intellisense`字段的包，并且读取配置
> 
> ```json
> {
>   "name": "@abc/ui"
>   "common-intellisense": {
>     "uiConfig": "./common-intellisense",
>     "name": "abcui"
>   }
> }
> ```
> 
> ```js
> import { propsReducer, componentsReducer,  } from '@xxx/abc/common-intellisense'
> // constants.ts的内容补充 
> // UINames ==> @xxx/abc
> // nameMap ==> {'@xxx/abc': 'abcui' }
> ```
> 
> 也能文档更新了也能及时识别更新
> 
> 之前的@vue/cli好像就扫描了前缀是vue-plugin-之类的包然后内部自动注册
> 
> 如果可以的话我可以尝试这个PR by the way: 数据字段的文档也需要补充，现在只能先看照描画虎，先看其他人的定义，或者去看源码了解可以配置那些字段

pr welcome

**Comment by chenyulun** [comment]
> > 把项目的dependencies的依赖都扫一遍，然后找到对应包的`package.json` 并且找到有定义`common-intellisense`字段的包，并且读取配置
> > ```json
> > {
> >   "name": "@abc/ui"
> >   "common-intellisense": {
> >     "uiConfig": "./common-intellisense",
> >     "name": "abcui"
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > import { propsReducer, componentsReducer,  } from '@xxx/abc/common-intellisense'
> > // constants.ts的内容补充 
> > // UINames ==> @xxx/abc
> > // nameMap ==> {'@xxx/abc': 'abcui' }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 也能文档更新了也能及时识别更新
> > 之前的@vue/cli好像就扫描了前缀是vue-plugin-之类的包然后内部自动注册
> > 如果可以的话我可以尝试这个PR by the way: 数据字段的文档也需要补充，现在只能先看照描画虎，先看其他人的定义，或者去看源码了解可以配置那些字段
> 
> pr welcome

大佬，你代码里面的`anyscript`大法给我打蒙了
我看源码太费劲了，注释也没有，
暂时看到每个组件的类型和处理这些json的逻辑
`import { componentsReducer, propsReducer } from '../../utils'`这个代码好像提取出来，导出的时候再去包裹执行，
这样其他的包里面导出只写`json`+`mapping.mjs`+ `index.mjs`
其中`index.mjs`
```js
import { getComponentMap, getPropsMap } from './mapping.mjs'

export function getPropsConfig() {
  return {
    // uiName: 'vant4', // 引用的地方可以获取，不需要填写，组件编写方不应该关注版本，在package.json里面都写了name和version
    map: getPropsMap(),
    lib: 'vant',
    prefix: 'van',
  }
}

export function getComponentsConfig() {
  return {
    map: getComponentMap(),
    isSeperatorByHyphen: true,
    prefix: 'van',
    lib: 'vant',
  }
}
```

**Comment by Simon-He95** [comment]
@chenyulun 单独开一个 feat 的 issue，来讨论吧

**Comment by Simon-He95** [comment]
> [Moonofweisheng](/Moonofweisheng)

我已经为 wot-design-uni搭建好了仓库，如果你感兴趣的话，可以 pr 参考其他的 UI 去提供一下对应的配置文件
https://github.com/common-intellisense/wot-design-uni1/issues/1
另外现在仓库已经重构了，后续开发都会在 https://github.com/common-intellisense/common-intellisense
问题反馈可以发到 https://github.com/common-intellisense/common-intellisense/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

**Comment by chenyulun** [comment]
@Simon-He95 呕心沥血干了好几天了，辛苦了

**Comment by chenyulun** [comment]
大佬， 我内网状态下，导致我da打开ts和vue文件都巨慢，

<img width="538" alt="image" src="https://github.com/user-attachments/assets/057b0a12-f78e-4a4f-90c4-5159cf9cc9f7">

必须等这个结果失败之后才能打开

**Comment by chenyulun** [comment]
大佬，内网情况下，这个插件会卡我打开`ts`和`vue`很久
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/8627c3e2-83f9-4a00-b109-a8c1fe288860">
只有最后失败的时候才能打开`vue`或者`ts`

<img width="465" alt="image" src="https://github.com/user-attachments/assets/e68b4926-8de9-42ff-bf02-0ed523931d48">

**Comment by Moonofweisheng** [comment]
> > [Moonofweisheng](/Moonofweisheng)
> 
> 我已经为 wot-design-uni搭建好了仓库，如果你感兴趣的话，可以 pr 参考其他的 UI 去提供一下对应的配置文件 [common-intellisense/wot-design-uni1#1](https://github.com/common-intellisense/wot-design-uni1/issues/1) 另外现在仓库已经重构了，后续开发都会在 https://github.com/common-intellisense/common-intellisense 问题反馈可以发到 https://github.com/common-intellisense/common-intellisense/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

好的，感谢。

**Comment by Simon-He95** [comment]
@chenyulun v0.2.4 尝试一下这个版本

**Comment by Simon-He95** [comment]
migrate to https://github.com/common-intellisense/common-intellisense/issues/3

**Comment by Simon-He95** [comment]
@Moonofweisheng Moo [common-intellisense/wot-design-uni](https://github.com/common-intellisense/wot-design-uni/tree/version-1) 已经集成了，你可以根据组件的上的一些必须属性等等去调整，增强 DX
