### ISSUE TITLE
ant-design-vue 1.x 报错 defaultValue.replace is not a function

### ISSUE THREAD

**Issue by moohao** [Simon-He95/common-intellisense#74]
![image](https://github.com/user-attachments/assets/d67d9440-380c-42d5-8ee1-ed17791f67b6)

**Comment by Simon-He95** [comment]
我复现不了，能提供一些更具体是操作步骤和场景吗

**Comment by moohao** [comment]
`src/ui/utils.ts`
`let value = defaultValue.replace(/\s+/g, ' ').replace(/\|/g, ' \\| ').trim()`
我看好多json配置里面default值是非字符串，导致了错误。

**Comment by Simon-He95** [comment]
> `src/ui/utils.ts` `let value = defaultValue.replace(/\s+/g, ' ').replace(/\|/g, ' \\| ').trim()` 我看好多json配置里面default值是非字符串，导致了错误。

不会吧 json 里面都是字符串吧

**Comment by moohao** [comment]
`src/ui/elementUi/elementUi2/table.json`
里面的`show-header`的`"default": true,`
json配置default值存在数字和布尔

**Comment by Simon-He95** [comment]
> show-header

nice catch

**Comment by Simon-He95** [comment]
v0.1.66 should fix
