### ISSUE TITLE
don't support for .tsx file

### ISSUE THREAD

**Issue by HenryTSZ** [Simon-He95/common-intellisense#79]
![tsx](https://github.com/user-attachments/assets/da66ec3b-62b7-46fd-8923-bc026de1d2c3)

**Comment by Simon-He95** [comment]
Can you provide a simple demo to reproduce this?

**Comment by HenryTSZ** [comment]
```tsx
import React, { useState } from 'react';
import { Tree } from 'antd';

const App: React.FC = () => {
  const [data, setData] = useState<any>([]);

  return (
    <>
      {/* good */}
      <Tree></Tree>
      {/* bad */}
      {!!data.length && <Tree></Tree>}
      {/* good */}
      {data.length ? <Tree></Tree> : null}
    </>
  );
};

export default App;
```

**Comment by Simon-He95** [comment]
> ```tsx
> import React, { useState } from 'react';
> import { Tree } from 'antd';
> 
> const App: React.FC = () => {
>   const [data, setData] = useState<any>([]);
> 
>   return (
>     <>
>       {/* good */}
>       <Tree></Tree>
>       {/* bad */}
>       {!!data.length && <Tree></Tree>}
>       {/* good */}
>       {data.length ? <Tree></Tree> : null}
>     </>
>   );
> };
> 
> export default App;
> ```

<img width="874" alt="image" src="https://github.com/user-attachments/assets/3d85285c-20e3-4fde-a294-b09884920888">
It works for me, which antd's version you used

**Comment by HenryTSZ** [comment]
antd v4

<img width="901" alt="image" src="https://github.com/user-attachments/assets/e20463d6-8854-42a2-bc1b-182dcc559e5c">

<img width="493" alt="image" src="https://github.com/user-attachments/assets/d5d77690-5bac-4495-b68b-d251a3685da2">

**Comment by HenryTSZ** [comment]
add case

```tsx
import React, { useState } from 'react';
import { Button, Tree } from 'antd';

const App: React.FC = () => {
  const [data, setData] = useState<any>([]);

  return (
    <>
      {/* good */}
      <Tree></Tree>
      {/* bad */}
      {!!data.length && <Tree></Tree>}
      {/* good */}
      {data.length ? <Tree></Tree> : null}

      {/* good */}
      <Button></Button>
      {/* bad */}
      <Button>确定</Button>
    </>
  );
};

export default App;
```

**Comment by Simon-He95** [comment]
v0.1.73 has fixed, thanks for you help

**Comment by HenryTSZ** [comment]
@Simon-He95 Thank you for providing so many good plugins
