### ISSUE TITLE
index.ts的vscode.Position类型错误

### ISSUE THREAD

**Issue by chenyulun** [Simon-He95/common-intellisense#81]
if (position.active === ':' && result.type === 'text')

<img width="831" alt="image" src="https://github.com/user-attachments/assets/b9cc33c4-3bef-4b53-9818-944d32cd0f64">

**Comment by Simon-He95** [comment]
ah, it can be ignored

**Comment by chenyulun** [comment]
忽略的话运行会报错，说存在错误，是否继续，虽然可以继续，但是能不能修复一下，我还没调试到这里，暂时不懂这个active什么意思
他是之前有这个属性吗？
"@types/vscode": "1.77.0",
这个包里面的`Position`没有这个属性

**Comment by chenyulun** [comment]
other error:
![image](https://github.com/user-attachments/assets/a479bb3d-8088-414c-953e-72906ba9aaf5)


➜  github git clone https://github.com/Simon-He95/common-intellisense.git
Cloning into 'common-intellisense'...
remote: Enumerating objects: 18034, done.
remote: Counting objects: 100% (3628/3628), done.
remote: Compressing objects: 100% (1258/1258), done.
remote: Total 18034 (delta 2770), reused 3183 (delta 2358), pack-reused 14406 (from 1)
Receiving objects: 100% (18034/18034), 157.63 MiB | 8.78 MiB/s, done.
Resolving deltas: 100% (13985/13985), done.
Updating files: 100% (4285/4285), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/ui/varlet/varlet3/snackBar.json'
  'src/ui/varlet/varlet3/snackbar.json'
➜  github cd common-intellisense

**Comment by chenyulun** [comment]
fix code:

`index.ts:294`
```diff
- if (position.active === ':' && result.type === 'text')
+ if ((position as any).active === ':' && result.type === 'text')
```

`utils.ts:103`
```diff
- const targetInPositionNode = vineFileCtx.vineCompFns.find(item => isInPosition(item.fnDeclNode.loc, position))
+ const targetInPositionNode = vineFileCtx.vineCompFns.find(item => item.fnDeclNode.loc ? isInPosition(item.fnDeclNode.loc, position) : false)
```
`utils.ts:480`
```diff
- function findRef(children: any, map: any, refsMap: (string | [string, string])[]) {
+ function findRef(children: any, map: any, refsMap: (string | [string, string])[] = []) {
```
