### ISSUE TITLE
feat request: add config link to load remote UI

### ISSUE THREAD

**Issue by Simon-He95** [Simon-He95/common-intellisense#83]
@chenyulun 我觉得大体上可以这样实现，在 vscode 初始化的时候可以读区一个 config 字段，比如 remoteUrls，然后检测这个字段是否有值，然后发请求去拿数据，然后需要 merge 进 [constant](https://github.com/Simon-He95/common-intellisense/blob/main/src/constants.ts) 中，和 通过 propsReducer 和 componentsReducer 去合并到 (UI)[https://github.com/Simon-He95/common-intellisense/blob/main/src/index.ts#L808] 中，应该就可以实现了，参考一下 UI 中的数据结构

再来解释一下为什么需要版本，因为每一个大版本都可能有很大的 breaking change，甚至完全 api 组件都变了，所以要区分版本，如果有什么困惑欢迎随时讨论：）

**Comment by chenyulun** [comment]
列举了需要处理的事项：
- [ ] 1. 定义组件描述的`json`，并且编写TS类型
- [ ] 2. icon的预览绝对路径应该有组件自己定义，不应该放到公共函数里面组合处理
- [ ] 3. 对原始数据的处理迁移到组件配置外面，并且定义传入参数
- [ ] 4. 初始化读取`package.json`并且找到对于包里面的插件配置与默认支持的配置合并


这些组件的描述文件随着包一起发布，包里面的组件描述配置肯定是与这个代码API最契合的，版本也不需要再组件描述文件里面体现

**Comment by chenyulun** [comment]
其实内置的这些组件也应该拆出去，和`@types/xxxx`一样进行发布，也能保持版本对于，最后都推动包的维护者写到他们自己的npm包里面发布，这样插件的API数据类型对外公布，按约定来，这样插件也不需要频繁更新了

**Comment by Simon-He95** [comment]
> 其实内置的这些组件也应该拆出去，和`@types/xxxx`一样进行发布，也能保持版本对于，最后都推动包的维护者写到他们自己的npm包里面发布，这样插件的API数据类型对外公布，按约定来，这样插件也不需要频繁更新了

我非常认同这个观点

**Comment by chenyulun** [comment]
还有一种方式是，通过定义配置文件`common-intellisense.config.mjs`（类似eslint），UI组件npm包预留号配置文件
```mjs
// import { getPropsConfig, getComponentsConfig } from 'vant/common-intellisense'
import vantUIConfig from 'vant/common-intellisense'
export default function (extensionContext) {
// 这里的配置我没想好需要包含那些,需要讨论
return {
extends: [vantUIConfig(extensionContext)]

//    uiConfig: {
//      vant: {getPropsConfig, getComponentsConfig}
//   }
}
}
```

**Comment by Simon-He95** [comment]
> 还有一种方式是，通过定义配置文件`common-intellisense.config.mjs`（类似eslint），UI组件npm包预留号配置文件
> 
> ```js
> // import { getPropsConfig, getComponentsConfig } from 'vant/common-intellisense'
> import vantUIConfig from 'vant/common-intellisense'
> export default function (extensionContext) {
> // 这里的配置我没想好需要包含那些,需要讨论
> return {
> extends: [vantUIConfig(extensionContext)]
> 
> //    uiConfig: {
> //      vant: {getPropsConfig, getComponentsConfig}
> //   }
> }
> }
> ```

可以这样，既有远程的 link 获取然后 merge 到 UI，这样可以支持公司内部的 UI 库，也有根据当前 UI 库支持的公共开源组件，然后单独发 npm 包，通过一个脚本去获取比如我当前用了 element2，去拉取 @common-intellisense/element2 的最新版本 unpkg 或者 jsdeliver 文件

**Comment by chenyulun** [comment]
之前还能动态爬取配置合并到插件吗？我写了一版初版：
主要改动：
1. 整理ts类型
2. `index.ts`过大拆分，还有解除互相引用
3. 支持扫描package.json里面的配置文件并且加载，但是如果包里面有json不知道能不能加载，我还需要测试一下
4. 标记了有三方参数入参错误的问题
大佬如果有空先看看，我晚上换电脑在回去测试一下，
https://github.com/chenyulun/common-intellisense/tree/featrue-1

**Comment by Simon-He95** [comment]
非常感谢你积极的参与，由于改动量有些大，我这边已经有了一些解决方案，可以再我之后更新的版本去再次重构，目前是用了动态读取 unpkg 和 jsdelivr 将其他 UI 单独发包，然后读取最新版本的策略，然后我这边已经测试过了，正在大改，我邀请你加入了，感兴趣的话可以再我之后的版本去迭代

**Comment by chenyulun** [comment]
好的，index.ts裡面昨晚修改ts的時候發現多了個數組括號，

**Comment by Simon-He95** [comment]
https://github.com/common-intellisense/common-intellisense
