### ISSUE TITLE
正在拉取远程的 antd5: 已完成 99%

### ISSUE THREAD

**Issue by DrRua** [Simon-He95/common-intellisense#84]
![image](https://github.com/user-attachments/assets/7902ad7c-0118-426d-8e92-9faec0589d34)
正在拉取远程的 antd5: 已完成 99%
![image](https://github.com/user-attachments/assets/32c1cac3-76fa-4d53-adfc-9a8cf0b690dd)
正在拉取远程的 naive-ui2: 已完成 99%

**Comment by Simon-He95** [comment]
现在已经重构成动态拉取 npm 上的资源了，之前是在插件中打包出来会体积比较大，这个进度是预期的

**Comment by DrRua** [comment]
> 现在已经重构成动态拉取 npm 上的资源了，之前是在插件中打包出来会体积比较大，这个进度是预期的

原来如此，那antd5预期会耗费多少时间？从早上九点打开vscode到十一点半还卡在99%...

**Comment by Simon-He95** [comment]
> > 现在已经重构成动态拉取 npm 上的资源了，之前是在插件中打包出来会体积比较大，这个进度是预期的
> 
> 原来如此，那antd5预期会耗费多少时间？从早上九点打开vscode到十一点半还卡在99%...

。。。应该1分钟左右就能加载完了,可能是代理的问题

**Comment by DrRua** [comment]
> > > 现在已经重构成动态拉取 npm 上的资源了，之前是在插件中打包出来会体积比较大，这个进度是预期的
> > 
> > 
> > 原来如此，那antd5预期会耗费多少时间？从早上九点打开vscode到十一点半还卡在99%...
> 
> 。。。应该1分钟左右就能加载完了,可能是代理的问题

应该是这个问题，我开了全局代理后成功拉到包了

**Comment by niaodan2b** [comment]
这个不会走.npmrc里配置的镜像吗
