### ISSUE TITLE
一直在加载 load project 

### ISSUE THREAD

**Issue by xiaojia21190** [Simon-He95/common-intellisense#85]
已经无法使用了

**Comment by xiaojia21190** [comment]
![image](https://github.com/user-attachments/assets/39f64872-3474-4979-9d99-bfccdd94a2bb)

**Comment by Simon-He95** [comment]
用v0.2.4的版本尝试一下

**Comment by xiaojia21190** [comment]
麻烦了，还有一个问题，就是每一次打开项目，有概率无法加载， 其他插件也停止了，没有任何信息，需要启动，触发进度才可以继续操作

**Comment by Simon-He95** [comment]
用了最新的版本还会吗，有复现的gif吗

**Comment by Simon-He95** [comment]
可以查看一下 vscode 的 output 日志有没有什么报错之类的 
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/3a439ec9-629c-4dec-bfc4-817f942bc777">

**Comment by xiaojia21190** [comment]
目前没发现错误，正在load project

**Comment by xiaojia21190** [comment]
![image](https://github.com/user-attachments/assets/7d6e3b47-bce5-4330-a2b9-29f38963bc29)
这是正常情况， 非正常情况就是一直 load project

**Comment by Simon-He95** [comment]
你这个不是最新版本吧的截图吧

**Comment by xiaojia21190** [comment]
![image](https://github.com/user-attachments/assets/02dd9934-fcd0-4853-9bf8-ece23054ad97)
这是最新的

**Comment by Simon-He95** [comment]
你本地开代理了吗，因为 unpkg 和 jsdelivr需要梯子才能拉下来

**Comment by xiaojia21190** [comment]
有代理，但不是全局的

**Comment by Simon-He95** [comment]
duplicated: #89
