### ISSUE TITLE
bug: 使用quasar 2没有提示，mapping.json中只有antd5配置信息

### ISSUE THREAD

**Issue by Ming-Jie** [Simon-He95/common-intellisense#86]
![image](https://github.com/user-attachments/assets/3475ca1d-be72-4de0-90f6-462adb4cf817)
![image](https://github.com/user-attachments/assets/25f308e0-7a1f-459d-9bdf-eef830132488)

**Comment by Simon-He95** [comment]
v0.2.5 has fixed
