### ISSUE TITLE
bug: pnpm workspace 中不提示

### ISSUE THREAD

**Issue by sunven** [Simon-He95/common-intellisense#87]
如果依赖装在了 根 中，那么单个包中的代码不提示
![image](https://github.com/user-attachments/assets/e732c9a8-cf79-42ac-8735-408c874f422c)

**Comment by Simon-He95** [comment]
是的，他只检测当前环境最近的一个 `package.json`, 一般 UI 组件库也是装在当前包中，所以这个问题是不考虑解决，你可以在这个目录下 `package.json`, 去追加一个 `antd` 的依赖，就有提示了
