### ISSUE TITLE
vant提示不生效

### ISSUE THREAD

**Issue by Lennonxc** [Simon-He95/common-intellisense#88]
插件版本：v0.2.4
vant版本：v4.9.6
如图所示，vant提示不生效，安装插件和vant后并没有弹出“正在拉取远程的 ‘xxxx’”的提示，在使用element时正常
![PixPin_2024-09-20_10-46-03](https://github.com/user-attachments/assets/243e1aba-19ec-400c-9e3a-5a15e35474fe)
![image](https://github.com/user-attachments/assets/179ef725-4261-4145-b939-bdbf6053c0be)

**Comment by Simon-He95** [comment]
能提供一下vscode的输出信息吗
<img width="1598" alt="image" src="https://github.com/user-attachments/assets/2a83f099-b7ad-4a68-92f5-b61f6408cdf1">

**Comment by Lennonxc** [comment]
vscode的输出信息里面没有Common Intellisense选项呢
![PixPin_2024-09-20_16-27-44](https://github.com/user-attachments/assets/62d00929-0a4c-4366-8cf9-7a531ec338dc)

**Comment by Simon-He95** [comment]
卸载重新安装试试呢:p

**Comment by Lennonxc** [comment]
现在卸载重装v0.2.5新版本可以了，v0.2.4版本时重装了几次都不可以

**Comment by Simon-He95** [comment]
👌
