### ISSUE TITLE
v0.2.5 一直显示“正在在拉取远程的 element-plus2: 已完成 99%”

### ISSUE THREAD

**Issue by iizyd** [Simon-He95/common-intellisense#89]
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/ce2674bd-9ea2-430d-9092-bf3c28b2bc38">

**Comment by Simon-He95** [comment]
你当前环境有代理吗，目前最新的改动需要有代理的情况下才行

**Comment by iizyd** [comment]
> 你当前环境有代理吗，目前最新的改动需要有代理的情况下才行

有的，全局代理，更新到最新还是不行

**Comment by Simon-He95** [comment]
感觉你本地似乎有多个版本的 common-intellisense 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/97581ea4-26f4-47e6-aa06-938cea62b898">
把 common-intellisense 的都删除干净再重新安装试试

**Comment by iizyd** [comment]
> 感觉你本地似乎有多个版本的 common-intellisense <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/57086651/369800407-97581ea4-26f4-47e6-aa06-938cea62b898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODU5OTYsIm5iZiI6MTcyNzA4NTY5NiwicGF0aCI6Ii81NzA4NjY1MS8zNjk4MDA0MDctOTc1ODFlYTQtMjZmNC00N2U2LWFhMDYtOTM4Y2VhNjJiODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEwMDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NGIzM2JjYWU4YWE2MjdmOWFmMGQzOTMwOWNiYzcyNmU4YWIwMjE4YTVlOTNiMzMyZWE3NjJkMTIyNGQ2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oW0NfXJOiUxDifb7qTt9DcwltNIRt3LLoxR4NCZ0qSk"> 把 common-intellisense 的都删除干净再重新安装试试

确实有，但是我也试来着，把 simonhe 开头的都删了，插件卸载，重启 vscode，然后再安装，还是可以复现的

**Comment by Simon-He95** [comment]
我本地很快就能加载出来，不知道是否是mac和win上的差异导致的，如果十分钟没有拉取成功理论上会返回错误消息，应该是代理的问题

**Comment by Simon-He95** [comment]
我尝试用了更多的镜像源去下载远程文件，可以尝试升级到最新版的试试

**Comment by iizyd** [comment]
> 我尝试用了更多的镜像源去下载远程文件，可以尝试升级到最新版的试试

好的，感谢

**Comment by Simon-He95** [comment]
你尝试一下直接在终端执行 `npm show @common-intellisense/element-plus2` 试试呢

**Comment by iizyd** [comment]
> 你尝试一下直接在终端执行 `npm show @common-intellisense/element-plus2` 试试呢

昨天直接在终端执行 `npm show @common-intellisense/element-plus2` 是可以的，今天安装最新的 `v0.2.12` 可以正常使用了
