### ISSUE TITLE
使用新版本后会一直显示“正在加载intelliSense”状态

### ISSUE THREAD

**Issue by Wong-Harry** [Simon-He95/common-intellisense#90]
![image](https://github.com/user-attachments/assets/48e344da-9d8c-480c-86c9-da4a995b5050)

目前切换回去旧版本就没这问题
![image](https://github.com/user-attachments/assets/cdb48e12-19b6-4aa1-92c6-c0f2400c432a)

**Comment by Simon-He95** [comment]
你当前环境有代理吗，目前最新的改动需要有代理的情况下才行

**Comment by Simon-He95** [comment]
duplicated: #89

**Comment by Wong-Harry** [comment]
> 你当前环境有代理吗，目前最新的改动需要有代理的情况下才行

有使用，但也不行

**Comment by Simon-He95** [comment]
> > 你当前环境有代理吗，目前最新的改动需要有代理的情况下才行
> 
> 有使用，但也不行。代理设置是全局

请尝试卸载重新安装，然后提供一份 vscode 中 common-intellisense 的输出，和一个加载时候的表现的gif，方便做排查

**Comment by iizyd** [comment]
> > > 你当前环境有代理吗，目前最新的改动需要有代理的情况下才行
> > 
> > 
> > 有使用，但也不行。代理设置是全局
> 
> 请尝试卸载重新安装，然后提供一份 vscode 中 common-intellisense 的输出，和一个加载时候的表现的gif，方便做排查

我也有这个情况，卸载重装也不行

https://github.com/Simon-He95/common-intellisense/issues/89
