### ISSUE TITLE
本插件的v0.2.5版本，和vscode v1.93.1版本不兼容

### ISSUE THREAD

**Issue by yxl0520** [Simon-He95/common-intellisense#91]
本插件的v0.2.5版本，和vscode v1.93.1版本不兼容，会导致vscode的其他各个插件加载不成功的异常情况

**Comment by Simon-He95** [comment]
新版本采用了动态获取远程包的情况，依赖 npk 和 jsdelivr 所以是需要代理的情况，但是他解决了每一次小的改动就需要频繁的发插件包来更新的问题，包的体积也减小了一半多，如果你有一些不成功的截图或者vscode的错误日志那时更好了，不过很大概率是因为代理的问题

**Comment by Simon-He95** [comment]
https://github.com/common-intellisense/common-intellisense/blob/main/README_zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
