### ISSUE TITLE
[ERROR] AggregateError: All promises were rejected

### ISSUE THREAD

**Issue by zhoushengdong** [Simon-He95/common-intellisense#93]
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/05bcf367-fb25-4f5c-b502-5c6ca5672514">

有挂代理。根据提供的步骤操作，但是没有生效！

**Comment by zhoushengdong** [comment]
找到问题了，是权限不够

**Comment by iilitlleboyii** [comment]
请问你是怎么解决的，我也有这个问题

**Comment by Simon-He95** [comment]
> 请问你是怎么解决的，我也有这个问题

[Universal Component Intellisense for Any Frameworks](https://github.com/common-intellisense/common-intellisense/blob/main/README_zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by iilitlleboyii** [comment]
> > 请问你是怎么解决的，我也有这个问题
> 
> [Universal Component Intellisense for Any Frameworks](https://github.com/common-intellisense/common-intellisense/blob/main/README_zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

还是不行诶，不知道代理有啥问题，github都能正常上，安装以前不需要代理的旧版本是好的

**Comment by Simon-He95** [comment]
> > > 请问你是怎么解决的，我也有这个问题
> > 
> > 
> > [Universal Component Intellisense for Any Frameworks](https://github.com/common-intellisense/common-intellisense/blob/main/README_zh.md?rgh-link-date=2024-10-12T15%3A22%3A54Z#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
> 
> 还是不行诶，不知道代理有啥问题，github都能正常上，安装以前不需要代理的旧版本是好的

1. 你可以尝试直接将 https://github.com/common-intellisense 下支持的 UI 库的 dist/index.cjs 下载到本地，然后从 `common-intellisense.localUris` 配置文件路径，从本地加载一次然后它会在本地缓存，以前是所有的 UI 库到在插件中加载，插件会很大，现在都是托管在 NPM 中去动态按需加载(这个和网络和梯子代理都有关系，不过我这里好像没遇到拉取不下来的问题)，并缓存在本地了
2. 你仍然可以使用 0.1 前的包 :P

**Comment by iilitlleboyii** [comment]
> > > > 请问你是怎么解决的，我也有这个问题
> > > 
> > > 
> > > [Universal Component Intellisense for Any Frameworks](https://github.com/common-intellisense/common-intellisense/blob/main/README_zh.md?rgh-link-date=2024-10-12T15%3A22%3A54Z#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
> > 
> > 
> > 还是不行诶，不知道代理有啥问题，github都能正常上，安装以前不需要代理的旧版本是好的
> 
> 1. 你可以尝试直接将 https://github.com/common-intellisense 下支持的 UI 库的 dist/index.cjs 下载到本地，然后从 `common-intellisense.localUris` 配置文件路径，从本地加载一次然后它会在本地缓存，以前是所有的 UI 库到在插件中加载，插件会很大，现在都是托管在 NPM 中去动态按需加载(这个和网络和梯子代理都有关系，不过我这里好像没遇到拉取不下来的问题)，并缓存在本地了
> 2. 你仍然可以使用 0.1 前的包 :P

好滴，主要是三台电脑网络环境一样的，一个可以两个不可以，很奇怪

**Comment by zhoushengdong** [comment]
> 请问你是怎么解决的，我也有这个问题

权限不够导致的，你可以试试提示权限
Windows：右键管理员运行
Mac：命令行运行 code .

**Comment by Simon-He95** [comment]
现在提供了一个 [common-intellisense-local](https://marketplace.visualstudio.com/items?itemName=simonhe.common-intellisense-local) 的包, 考虑到内网和无网络的情况使用

**Comment by iilitlleboyii** [comment]
> 现在提供了一个 [common-intellisense-local](https://marketplace.visualstudio.com/items?itemName=simonhe.common-intellisense-local) 的包, 考虑到内网和无网络的情况使用


爱了爱了
